site_name: lume-epics
nav:
  - Home: index.md
  - Install: Install.md
  - Quick Start: QuickStart.md
  - Documentation:
    - Client:
      - Controller: Controller.md
      - Monitors: Monitors.md
      - Widgets: Widgets.md
    - Model: Model.md
    - Server: Server.md
theme: material
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            inherited_members: false
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
          rendering:
            show_source: true
