
model:
    model_class: lume_model.keras.KerasModel
    requirements:
      tensorflow: 2.3.1
    kwargs:
      model_file: examples/files/iris_model.h5
    output_format:
        type: softmax


input_variables:
    SepalLength:
        name: SepalLength
        type: scalar
        default: 4.3
        range: [4.3, 7.9]

    SepalWidth:
        name: SepalWidth
        type: scalar
        default: 2.0
        range: [2.0, 6.9]

    PetalLength:
        name: PetalLength
        type: scalar
        default: 1.0
        range: [1.0, 6.9]

    PetalWidth:
        name: PetalWidth
        type: scalar
        default: 0.1
        range: [0.1, 2.5]

output_variables:
    Species:
        name: Species
        type: scalar
