name: Build lume-epics

on:
  push:
    branches:    
      - master
      - github-actions

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
        run: |

          conda info
          conda --set always_yes yes --set changeps1 no
          conda --add channels conda-forge
          conda --set channel_priority strict
          conda config --append channels jrgarrahan # temporary lume-model fix
          conda install conda-build anaconda-client
          cconda update -q conda conda-build
      - name: Build package
        run: |
          conda build -q conda-recipe --python=$TRAVIS_PYTHON_VERSION --output-folder bld-dir
      - name: Test with pytest
        run: |
          conda config --add channels "file://`pwd`/bld-dir"
          conda create -q -n test-environment --file dev-requirements.txt
          conda activate test-environment
          pytest
