
name: Build docs

on:
  push:
    branches:    
      - master
      - github-actions
jobs:
  build:
    #if: ${{ github.repository == 'slaclab/lume-epics' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    name:  Build docs
    steps:
      - uses: actions/checkout@v2
      - name: Set up conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      - name: Configure conda
        run: |
          conda info
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          conda install conda-build anaconda-client
          conda install --file dev-requirements.txt
          conda install --file docs-requirements.txt
      - name: Make docs
        run: |
          mkdocs build
          mkdocs gh-deploy
          