name: Build lume-epics

on:
  push:
    branches:    
      - master
      - github-actions

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - name: Set up conda
        run: |
          # $CONDA points to the root of the miniconda directory
          $CONDA/bin/conda --set always_yes yes --set changeps1 no
          $CONDA/bin/conda --add channels conda-forge
          $CONDA/bin/conda --set channel_priority strict
          $CONDA/bin/conda config --append channels jrgarrahan # temporary lume-model fix
          $CONDA/bin/conda install conda-build anaconda-client
          $CONDA/bin/conda update -q conda conda-build
      - name: Build package
        run: |
          $CONDA/bin/conda build -q conda-recipe --python=$TRAVIS_PYTHON_VERSION --output-folder bld-dir
      - name: Test with pytest
        run: |
          $CONDA/bin/conda config --add channels "file://`pwd`/bld-dir"
          $CONDA/bin/conda create -q -n test-environment --file dev-requirements.txt
          $CONDA/bin/conda activate test-environment
          pytest
